# Create Athena Database

In [1]:
import boto3
import sagemaker

sess = sagemaker.Session()
bucket = sess.default_bucket()
role = sagemaker.get_execution_role()
region = boto3.Session().region_name

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml

In [2]:
ingest_create_athena_db_passed = False

In [3]:
%store -r s3_private_path_wav

In [4]:
try:
    s3_private_path_wav
except NameError:
    print("*****************************************************************************")
    print("[ERROR] PLEASE RE-RUN THE PREVIOUS COPY TSV TO S3 NOTEBOOK ******************")
    print("[ERROR] THIS NOTEBOOK WILL NOT RUN PROPERLY. ********************************")
    print("*****************************************************************************")

In [5]:
print(s3_private_path_wav)

s3://sagemaker-us-east-1-218117716191/audio/Datasets/

## Import PyAthena

In [6]:
from pyathena import connect

## Ceate Athena Database

In [7]:
database_name = "audio_emotions"

In [8]:
# Set S3 staging directory -- this is a temporary directory used for Athena queries
s3_staging_dir = "s3://sagemaker-us-east-1-218117716191/athena/staging/" #Our directory

In [9]:
conn = connect(s3_staging_dir=s3_staging_dir, region_name=region, )

In [10]:
statement = "CREATE DATABASE IF NOT EXISTS {}".format(database_name)
print(statement)

CREATE DATABASE IF NOT EXISTS audio_emotions

In [11]:
import pandas as pd

pd.read_sql(statement, conn)

/tmp/ipykernel_1253/3803073958.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(statement, conn)

Empty DataFrame
Columns: []
Index: []

## Verify The Database Has Been Created Successfully

In [12]:
statement = "SHOW DATABASES"

df_show = pd.read_sql(statement, conn)
df_show.head(5)

/tmp/ipykernel_1253/3999478089.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_show = pd.read_sql(statement, conn)

    database_name
0          am2aws
1  audio_emotions
2         default
3          dsoaws
4          hm2aws

In [13]:
if database_name in df_show.values:
    ingest_create_athena_db_passed = True

In [14]:
%store ingest_create_athena_db_passed

Stored 'ingest_create_athena_db_passed' (bool)

## Store Variables for the Next Notebooks

In [15]:
%store

Stored variables and their in-db values:
ingest_create_athena_db_passed             -> True
s3_file_path_wav                           -> 's3://sagemaker-us-east-1-218117716191/audio/Datas
s3_private_path_wav                        -> 's3://sagemaker-us-east-1-218117716191/audio/Datas
setup_dependencies_passed                  -> True
setup_s3_bucket_passed                     -> True

## Release Resources

In [16]:
%%html

<p><b>Shutting down your kernel for this notebook to release resources.</b></p>
<button class="sm-command-button" data-commandlinker-command="kernelmenu:shutdown" style="display:none;">Shutdown Kernel</button>
        
<script>
try {
    els = document.getElementsByClassName("sm-command-button");
    els[0].click();
}
catch(err) {
    // NoOp
}    
</script>

In [1]:
%%javascript

try {
    Jupyter.notebook.save_checkpoint();
    Jupyter.notebook.session.delete();
}
catch(err) {
    // NoOp
}